repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: go-mod-tidy
      - id: go-vet-mod
      - id: go-build-mod
      - id: golangci-lint-mod
        args: [--timeout=5m]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: mixed-line-ending
        args: [--fix=lf]

exclude: |
  (?x)^(
    \.git/|
    bin/|
    dist/|
    vendor/|
    test-.*/$
  )$